### ISSUE TITLE
Archetype for Vert.x 3

### ISSUE THREAD

**Issue by thierryler** [vert-x/vertx-maven#43]
Hello,

Are you planning to write an archetype for Vert.x 3 ?

Thx,
Th.

**Comment by purplefox** [comment]
Vert.x 3 basically has a vanilla pom.xml so I'm not sure there would be much point.

**Comment by thierryler** [comment]
OK ;-) 

Can you regive the URL, pls. ?

Thx

**Comment by purplefox** [comment]
There's a simple Maven example in the examples repo:

https://github.com/vert-x3/vertx-examples/tree/master/maven-simplest

**Comment by purplefox** [comment]
So basically all you need is:

a) Add dependency to vertx-core
b) Set compiler to Java 8

**Comment by thierryler** [comment]
Well, very nice ! Thanks you so much.

Th.
